[tool.poetry]
name = "pyroll-integral-thermal"
version = "0.1.1"
description = "Plugin for PyRoll providing an integral approach for thermal modelling"
authors = [
    "Matthias Schmidtchen <matthias.schmidtchen@imf.tu-freiberg.de>",
    "Max Weiner <max.weiner@imf.tu-freiberg.de>",
    "Christoph Renzing <christoph.renzing@imf.tu-freiberg.de>",
]
license = "GPL-3.0-only"

[tool.poetry.dependencies]
python = "^3.10"
pyroll = "^0.3.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
